# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Administrator/Desktop/Digital-Recognition-master/project/spartan_cam.srcs/sources_1/ip/SPI_DEMO_0/SPI_DEMO_0.xci
# IP: The module: 'SPI_DEMO_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/Digital-Recognition-master/project/Users/Administrator/SPI/SPI.srcs/constrs_1/new/system.xdc
# XDC: The top module name and the constraint reference have the same name: 'SPI_DEMO_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Administrator/Desktop/Digital-Recognition-master/project/spartan_cam.srcs/sources_1/ip/SPI_DEMO_0/SPI_DEMO_0.xci
# IP: The module: 'SPI_DEMO_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/Digital-Recognition-master/project/Users/Administrator/SPI/SPI.srcs/constrs_1/new/system.xdc
# XDC: The top module name and the constraint reference have the same name: 'SPI_DEMO_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
